version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
  brightness_service:
    build:
      context: brightnessService
      dockerfile: Dockerfile
    ports:
      - "8893:8893"
    networks:
      - service_network

networks:
  service_network:
    name: service_network
    external: true

