version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    networks:
      - service_network
  brightness_service:
    build:
      context: brightness
      dockerfile: ../brightnessService/Dockerfile
    ports:
      - "8893:8893"
      - "27017:27017"
    networks:
      - service_network

networks:
  service_network:
    name: service_network
    external: true

