[versions]
vertx = "4.5.9"
junit = "5.10.3"
mongodb = "5.1.2"
vertxTest = "4.5.9"
gson = "2.11.0"
jacoco = "0.8.12"


[libraries]
vertx-core = {module = "io.vertx:vertx-core", version.ref = "vertx"}
vertx-web = {module = "io.vertx:vertx-web", version.ref = "vertx"}
vertx-web-client = {module = "io.vertx:vertx-web-client", version.ref = "vertx"}
vertx-mqtt = {module = "io.vertx:vertx-mqtt", version.ref = "vertx"}
vertx-test = {module= "io.vertx:vertx-junit5", version.ref = "vertxTest"}

junit-api = {module = "org.junit.jupiter:junit-jupiter-api", version.ref="junit"}
junit-engine = {module = "org.junit.jupiter:junit-jupiter-engine", version.ref="junit"}
mongodb-driver = {module = "org.mongodb:mongodb-driver-sync", version.ref="mongodb"}
gson = {module = "com.google.code.gson:gson", version.ref = "gson"}
jacoco = {module = "org.jacoco:org.jacoco.build", version.ref = "jacoco"}

[bundles]
vertx-dependencies = [
    "vertx-core",
    "vertx-web",
    "vertx-web-client",
    "vertx-mqtt",
    "vertx-test"
]

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:3.1.7"
javadocAggregate = "io.freefair.aggregate-javadoc-jar:8.6"
