name: ci

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Create mongo Docker container
        uses: ankane/setup-mongodb@v1
      - if: ${{ matrix.os != 'windows-latest'}}
        run: |
            mongosh --eval "db = connect( 'mongodb://localhost/greenhouse' );
                            db.greenhouse.insertMany( [
                            {
                              _id: '63af0ae025d55e9840cbc1fa',
                              plant: {
                                name: 'lemon',
                                description: 'is a species of small evergreen trees in the flowering plant family Rutaceae, native to Asia, primarily Northeast India (Assam), Northern Myanmar or China.',
                                minTemperature: 8.0,
                                maxTemperature: 35.0,
                                minBrightness: 4200.0,
                                maxBrightness: 130000.0,                                },
                                minSoilHumidity: 20.0,
                                maxSoilHumidity: 65.0,
                                minHumidity: 30.0,
                                maxHumidity: 80.0
                              },
                              modality: 'AUTOMATIC'
                            },
                            {
                              _id: '63b29b0a3792e15bae3229a7',
                                                            plant: {
                              name: 'lemon',
                              description: 'is a species of small evergreen trees in the flowering plant family Rutaceae, native to Asia, primarily Northeast India (Assam), Northern Myanmar or China.',
                              minTemperature: 8.0,
                              maxTemperature: 35.0,
                              minBrightness: 4200.0,
                              maxBrightness: 130000.0,
                              minSoilHumidity: 20.0,
                              maxSoilHumidity: 65.0,
                              minHumidity: 30.0,
                              maxHumidity: 80.0
                            },
                            modality: 'AUTOMATIC'
                          }
                          ])"
      - if: ${{ matrix.os == 'windows-latest' }}
        run: |
            mongo --eval "db = connect( 'mongodb://localhost/greenhouse' );
                            db.greenhouse.insertMany( [
                            {
                              '_id': {
                                '$oid': '63af0ae025d55e9840cbc1fa'
                              },
                              'plant': {
                                'name': 'lemon',
                                'description': 'is a species of small evergreen trees in the flowering plant family Rutaceae, native to Asia, primarily Northeast India (Assam), Northern Myanmar or China.',
                                'minTemperature': {
                                  '$numberDouble': '8.0'
                                },
                                'maxTemperature': {
                                  '$numberDouble': '35.0'
                                },
                                'minBrightness': {
                                  '$numberDouble': '4200.0'
                                },
                                'maxBrightness': {
                                  '$numberDouble': '130000.0'
                                },
                                'minSoilHumidity': {
                                  '$numberDouble': '20.0'
                                },
                                'maxSoilHumidity': {
                                  '$numberDouble': '65.0'
                                },
                                'minHumidity': {
                                  '$numberDouble': '30.0'
                                },
                                'maxHumidity': {
                                  '$numberDouble': '80.0'
                                }
                              },
                              'modality': 'AUTOMATIC'
                            },
                            {
                              '_id': {
                                '$oid': '63b29b0a3792e15bae3229a7'
                              },
                              'plant': {
                                'name': 'lemon AUTOMATIC',
                                'description': 'is a species of small evergreen trees in the flowering plant family Rutaceae, native to Asia, primarily Northeast India (Assam), Northern Myanmar or China.',
                                'minTemperature': {
                                  '$numberDouble': '8.0'
                                },
                                'maxTemperature': {
                                  '$numberDouble': '35.0'
                                },
                                'minBrightness': {
                                  '$numberDouble': '4200.0'
                                },
                                'maxBrightness': {
                                  '$numberDouble': '130000.0'
                                },
                                'minSoilHumidity': {
                                  '$numberDouble': '20.0'
                                },
                                'maxSoilHumidity': {
                                  '$numberDouble': '65.0'
                                },
                                'minHumidity': {
                                  '$numberDouble': '30.0'
                                },
                                'maxHumidity': {
                                  '$numberDouble': '80.0'
                                }
                              },
                              'modality': 'AUTOMATIC'
                            }
                          ])"
      - name: build
        run: ./gradlew build -x test
      - name: test
        run: ./gradlew test
  release:
    if: github.event_name == 'push'
    needs:
      - build
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          npm install
          npx semantic-release
  success:
    runs-on: ubuntu-latest
    needs:
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}